#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

date_default_timezone_set('Europe/Moscow');

use KubanOnline\Commands\CheckDoctorCommand;
use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();


$application = new Application();

// ... register commands




$application->add(new CheckDoctorCommand());

$application->run();

